/*
 * Project: 005led_toogle
 * Description: Basic STM32 project demonstrating fundamental concepts.
 * Author: omery
 */

/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include <stdint.h>
int main(void)
{
    /* Loop forever */

	uint32_t *pClockctrlreg = (uint32_t*)0x40023830;
	uint32_t *pPortDModereg = (uint32_t*)0x40020C00 ;
	uint32_t *pPortDoutReg = (uint32_t*)0x40020C14;

	//enable the clock
	/*uint32_t temp = *pClockctrlreg ;
	temp = temp | 0x08 ;
	*pClockctrlreg = temp ;*/
	//*pClockctrlreg |= 0x08;
	//usşng bitwise shift
	*pClockctrlreg |= (1<<3);

	// clear  24 25 output mode reset
	//*pPortDModereg &= 0xFCFFFFFF ;
	//usşng bitwise shift
	*pPortDModereg &= ~(3<<24);
	//*pPortDModereg &= ~(1<<25);
	//set
	//usşng bitwise shift

	*pPortDModereg |= (1<<24);
	//turnonport
	//usşng bitwise shift
	while(1){
		*pPortDoutReg |= (1<<12);
		for(uint32_t i = 0 ; i <100000 ; i++) ;
		*pPortDoutReg &= ~(1<<12);
		for(uint32_t i = 0 ; i <100000 ; i++) ;
	}
}
