/*
 * Project: 013led_toggle_bitfields
 * Description: Basic STM32 project demonstrating fundamental concepts.
 * Author: omery
 */

/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "main.h"


int main(void)
{
	uint8_t data = 0 ;

	RCC_AHB1ENR_t volatile *const pClockctrlreg = (RCC_AHB1ENR_t*)0x40023830;
	GPIOx_MODER_t volatile *const pPortDModereg = (GPIOx_MODER_t*)0x40020C00;
	GPIOx_MODER_t volatile *const pPortAModereg = (GPIOx_MODER_t*)0x40020000;
	GPIOx_ODR_t   volatile *const pPortDoutReg  = (GPIOx_ODR_t*)0x40020C14 ;
	GPIOx_IDR_t  volatile *const pApinreg = (GPIOx_IDR_t*)0x40020010 ;
	pClockctrlreg->gpiod_en = 0x01 ;
	pClockctrlreg->gpioa_en = 0x01 ;
	pPortAModereg->moder0 = 0  ;
	pPortDModereg->moder12 = 0x01 ;
	pPortDModereg->moder13 = 0x01 ;
	pPortDModereg->moder14 = 0x01 ;
	pPortDModereg->moder15 = 0x01 ;



	while (1) {
	    data = pApinreg->ıdr0;
	    pPortDoutReg->odr12 = 0x01;
	    pPortDoutReg->odr13 = 0x01;
	    pPortDoutReg->odr14 = 0x01;
	    pPortDoutReg->odr15 = 0x01;
	    for (volatile uint32_t i = 0; i < 500000; i++);
	    pPortDoutReg->odr12 = 0x00;
	    pPortDoutReg->odr13 = 0x00;
	    pPortDoutReg->odr14 = 0x00;
	    pPortDoutReg->odr15 = 0x00;
	    for (volatile uint32_t i = 0; i < 500000; i++);
	}



}
